### ISSUE TITLE
Can't get Pandora to play

### ISSUE THREAD

**Issue by Firestorrrm** [rectalogic/mopidy-pandora#50] opened 2016-04-15 16:50 UTC
Whenever I try to play a song through MusicBox, I get this error:

```
WARNING  Error changing Pandora track: Track(album=Album(name=u'(Company name not specified)'), artists=[Artist(name=u'(Title not specified)')], name=u'Advertisement', uri='pandora:ad:1033918586896730518:1033918586896730518-isa%3A1033918586896730518'), (Track with URI 'pandora:ad:1033918586896730518:1033918586896730518-isa%3A1033918586896730518' is not playable.)
WARNING  Track is not playable: pandora:ad:1033918586896730518:1033918586896730518-isa%3A1033918586896730518

** (<unknown>:2330): WARNING **: Invalid channel positions

** (<unknown>:2330): WARNING **: Invalid channel positions
ERROR    GStreamer error: gst-stream-error-quark: Internal data flow error. (1)
```

I set up everything in the config file, but I can't seem to get it to play anything. I'm running on the latest version of Mopidy and Mopidy-Pandora.

Thanks.

**Comment by jcass77** [comment] 2016-04-16 05:39
The log does not make it clear whether the problem is caused by gstreamer, or if gstreamer is just complaining about something that happens upstream in Mopidy-Pandora. Musicbox does not support Mopidy >= 2.0.0 or gstreamer-1.0 out of the box, so it is hard to tell if this might be an upstream issue. I've seen at least one other reference to the [gst-stream-error-quark: Internal data flow error)](https://github.com/mopidy/mopidy/issues/1479) issue for other backends as well.

If you still think this is specific to Mopidy-Pandora, it might be helpful if you could also share the following info:

Have you tried working through the [troubleshooting guide](https://github.com/rectalogic/mopidy-pandora/blob/develop/docs/troubleshooting.rst)?

Do you have gstreamer-1.0 and its associated plugins installed?

Does playback work for other Mopidy backends apart from Mopidy-Pandora?

Which platform / operating system are you running on?

Which version of `certifi` does `pip list` report that you have installed?

Does playback fail for **every** track or only advertisements?

**Comment by Firestorrrm** [comment] 2016-04-16 17:18
I just looked at the troubleshooting guide and still no luck.

I just installed gstreamer from their website.

Music plays for Spotify and everything else other than this backend.

Running on OS X El Capt

pip list shows:
`certifi (2015.4.28)`

Playback fails for every track.

Also, if I launch `pydora`, it works fine...

**Comment by jcass77** [comment] 2016-04-17 08:42
Could you confirm that you followed the Mopidy [installation instructions](http://mopidy.readthedocs.org/en/latest/installation/osx/) for OS X using Homebrew?

As far as I know the gstreamer plugins need to be installed with some optional build options enabled in order to fully support Mopidy (have a look at the [brew formula](https://github.com/mopidy/homebrew-mopidy/blob/master/mopidy.rb) for details). If you installed the binaries from the gstreamer website or built the plugins from source yourself then it is possible that support for the specific MPEG-1 Layer 3 (MP3) decoder was not baked in?

You could also try using one of the other partner [device types](https://6xq.net/pandora-apidoc/json/partners/#partners) which may serve up Pandora tracks using different encoders for you to try out on your setup.

**Comment by Firestorrrm** [comment] 2016-04-17 18:29
I followed the Mopidy installation instructions, I also reinstalled Mopidy ensuring I did.

Now I get this error when trying to play a Pandora station:

```
(<unknown>:669): GLib-GIO-ERROR **: Settings schema 'org.gnome.system.proxy' is not installed

Trace/BPT trap: 5
```
I also tried different device types and none of them are working. At this point I'm on the verge of not trying anymore.

**Comment by jcass77** [comment] 2016-04-18 03:58
There should be only two conditions under which tracks are not playable:

1. the track does not have an audio URL (this can happen for ads, but Mopidy-Pandora checks for this so it should not cause any problems).
2. pydora is not able to retrieve the HTTP headers for the URL (i.e. the track is not accessible. This can point to connectivity issues to the Pandora server, or problems with the Pandora account itself).

The default behaviour is for Mopidy-Pandora to just log a warning and skip to the next track, so I am not sure why it would repeat the last track played instead.

Could you post the contents of the tracklist when this happens again (if using Mopidy-Musicbox-Webclient this should be displayed on the 'Queue' page), and verify that another track has been lined up for playback after the advertisement?

**Comment by Firestorrrm** [comment] 2016-04-18 05:55
When the next song is an Advertisement, it shows this:

http://i.imgur.com/L800Gcx.png

If I try to skip the song, it will display this error message:

```
WARNING  Error changing Pandora track: Track(album=Album(name=u'(Company name not specified)'), artists=[Artist(name=u'(Title not specified)')], name=u'Advertisement', uri='pandora:ad:1737034235382286742:1737034235382286742-none'), (Track with URI 'pandora:ad:1737034235382286742:1737034235382286742-none' is not playable.)
WARNING  Track is not playable: pandora:ad:1737034235382286742:1737034235382286742-none
```

then will proceed towards replaying the last played song. Also, if I'm connected to Mopidy via ncmpcpp and an advertisement attempts to play, this spams the console:

```
INFO     New MPD connection from [::ffff:127.0.0.1]:59531
INFO     New MPD connection from [::ffff:127.0.0.1]:59532
INFO     New MPD connection from [::ffff:127.0.0.1]:59541
INFO     New MPD connection from [::ffff:127.0.0.1]:59544
INFO     New MPD connection from [::ffff:127.0.0.1]:59545
INFO     New MPD connection from [::ffff:127.0.0.1]:59546
INFO     New MPD connection from [::ffff:127.0.0.1]:59548
INFO     New MPD connection from [::ffff:127.0.0.1]:59555
INFO     New MPD connection from [::ffff:127.0.0.1]:59556
INFO     New MPD connection from [::ffff:127.0.0.1]:59557
WARNING  Rejected connection from [::ffff:127.0.0.1]:59560
WARNING  Rejected connection from [::ffff:127.0.0.1]:59561
WARNING  Rejected connection from [::ffff:127.0.0.1]:59562
WARNING  Rejected connection from [::ffff:127.0.0.1]:59563
WARNING  Rejected connection from [::ffff:127.0.0.1]:59564
WARNING  Rejected connection from [::ffff:127.0.0.1]:59565
WARNING  Rejected connection from [::ffff:127.0.0.1]:59566
WARNING  Rejected connection from [::ffff:127.0.0.1]:59567
WARNING  Rejected connection from [::ffff:127.0.0.1]:59568
WARNING  Rejected connection from [::ffff:127.0.0.1]:59569
WARNING  Rejected connection from [::ffff:127.0.0.1]:59570
WARNING  Rejected connection from [::ffff:127.0.0.1]:59571
WARNING  Rejected connection from [::ffff:127.0.0.1]:59572
WARNING  Rejected connection from [::ffff:127.0.0.1]:59573
WARNING  Rejected connection from [::ffff:127.0.0.1]:59574
WARNING  Rejected connection from [::ffff:127.0.0.1]:59576
WARNING  Rejected connection from [::ffff:127.0.0.1]:59577
WARNING  Rejected connection from [::ffff:127.0.0.1]:59578
WARNING  Rejected connection from [::ffff:127.0.0.1]:59579
WARNING  Rejected connection from [::ffff:127.0.0.1]:59580
WARNING  Rejected connection from [::ffff:127.0.0.1]:59581
WARNING  Rejected connection from [::ffff:127.0.0.1]:59582
```

After a while, the replayed song stops and plays a new song and the queue fills up with 2 new songs.

**Comment by jcass77** [comment] 2016-04-18 11:36
Mopidy 2.0.0 changed the way that unplayable tracks are handled: https://github.com/mopidy/mopidy/pull/1440, and this caused some issues with infinite loops that have since been fixed in the 'develop' branch, but not released yet: https://github.com/mopidy/mopidy/pull/1455.

It is possible that you are encountering a variation of that issue.

What is supposed to happen:

1. Mopidy-Pandora should enable ``consume`` mode by default, and disable ``repeat`` mode
2. Tracks should be removed from the tracklist when they have been played (i.e. consumed), or when they are unplayable (marked unplayable by Mopidy)
3. New tracks should be retrieved from the Pandora server and added to the tracklist as necessary.
4. https://github.com/rectalogic/mopidy-pandora/blob/eb92935c1dcc62e0d5bd337159b2901a3283658e/mopidy_pandora/playback.py#L73-L77 should enforce a limit on Mopidy skips to avoid infinite loops (which were an issue in previous versions of Mopidy as well). But looking at the latest Mopidy code it looks like the infinite loop might be occurring in the core, not the Mopidy-Pandora backend.

It could be that https://github.com/mopidy/mopidy/issues/1454 is causing an infinite loop while the Mopidy events are still being processed to update the tracklist and retrieve the next Pandora track. I'll have to dig a little to confirm and unfortunately don't have a working installation of Mopidy 2.0 on OSX at the moment, so replicating the issue for debugging might take a while.

If you don't want to wait then you could try using the latest 'develop' branch of Mopidy which contains the fix for https://github.com/mopidy/mopidy/issues/1454 to see if that improves the situation.

**Comment by Firestorrrm** [comment] 2016-04-18 13:34
How would I go about using the latest develop branch?

**Comment by jcass77** [comment] 2016-04-18 14:05
1. Uninstall the pip or brew version of Mopidy that you installed before (e.g. ``pip uninstall mopidy`` or ``brew uninstall --force mopidy``).

2. [Clone the repo from github](https://docs.mopidy.com/en/latest/devenv/#clone-the-repo-from-github) with ``git clone https://github.com/mopidy/mopidy.git``. You don't need to create the virtual environment or complete any of the other steps unless you plan on debugging Mopidy and making changes to the source code.

3. ``cd ~/<directory that you cloned the repo to>/``

4. Run ``python setup.py install``. Once this is done ``pip list`` should list Mopidy pointing to the folder that you cloned the repo to.

5. Run ``mopidy`` as before.

**Comment by Firestorrrm** [comment] 2016-04-18 14:21
Works perfectly. When it gets to an ad, it still displays the error, but it skips over it and plays the next song. Thank you!

**Comment by Firestorrrm** [comment] 2016-04-18 15:41
It worked once and now its doing the same thing as before.

**Comment by jcass77** [comment] 2016-04-20 14:49
I've installed Mopidy 2.0.0 on OS X El Capitan and unfortunately have not been able to reproduce this issue.

I do get the same error message in the log, but playback of the next track continues as expected without interruption or delay:

```
WARNING  Error changing Pandora track: Track(album=Album(name=u'(Company name not specified)'), artists=[Artist(name=u'(Title not specified)')], name=u'Advertisement', uri='pandora:ad:3077194621699907383:3077194621699907383-pod%3A1/2/1'), (Track with URI 'pandora:ad:3077194621699907383:3077194621699907383-pod%3A1/2/1' is not playable.)
WARNING  Track is not playable: pandora:ad:3077194621699907383:3077194621699907383-pod%3A1/2/1
WARNING  Error changing Pandora track: Track(album=Album(name=u'(Company name not specified)'), artists=[Artist(name=u'(Title not specified)')], name=u'Advertisement', uri='pandora:ad:3077194621699907383:3077194621699907383-pod%3A2/2/1'), (Track with URI 'pandora:ad:3077194621699907383:3077194621699907383-pod%3A2/2/1' is not playable.)
WARNING  Track is not playable: pandora:ad:3077194621699907383:3077194621699907383-pod%3A2/2/1
```

Output of ``mopidy deps``:

```
Executable: /usr/local/bin/mopidy
Platform: Darwin-15.4.0-x86_64-i386-64bit
Python: CPython 2.7.11 from /usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7
Mopidy: 2.0.0 from /Users/jcass/PycharmProjects/Mopidy/mopidy
  Pykka>=1.1: 1.2.1 from /usr/local/lib/python2.7/site-packages/Pykka-1.2.1-py2.7.egg
  requests>=2.0: 2.9.1 from /usr/local/lib/python2.7/site-packages
  setuptools: 20.7.0 from /usr/local/lib/python2.7/site-packages
  tornado>=2.3: 4.3 from /usr/local/lib/python2.7/site-packages/tornado-4.3-py2.7-macosx-10.11-x86_64.egg
    backports.ssl_match_hostname: 3.5.0.1 from /usr/local/lib/python2.7/site-packages/backports.ssl_match_hostname-3.5.0.1-py2.7.egg
    singledispatch: 3.4.0.3 from /usr/local/lib/python2.7/site-packages/singledispatch-3.4.0.3-py2.7.egg
      six: 1.10.0 from /usr/local/lib/python2.7/site-packages/six-1.10.0-py2.7.egg
    certifi: 2016.2.28 from /usr/local/lib/python2.7/site-packages/certifi-2016.2.28-py2.7.egg
    backports_abc>=0.4: 0.4 from /usr/local/lib/python2.7/site-packages/backports_abc-0.4-py2.7.egg
Mopidy-MusicBox-Webclient: 2.2.0 from /Users/jcass/PycharmProjects/Mopidy/mopidy-musicbox-webclient
  setuptools: 20.7.0 from /usr/local/lib/python2.7/site-packages
  Mopidy>=1.1.0: 2.0.0 from /Users/jcass/PycharmProjects/Mopidy/mopidy
    Pykka>=1.1: 1.2.1 from /usr/local/lib/python2.7/site-packages/Pykka-1.2.1-py2.7.egg
    requests>=2.0: 2.9.1 from /usr/local/lib/python2.7/site-packages
    setuptools: 20.7.0 from /usr/local/lib/python2.7/site-packages
    tornado>=2.3: 4.3 from /usr/local/lib/python2.7/site-packages/tornado-4.3-py2.7-macosx-10.11-x86_64.egg
      backports.ssl_match_hostname: 3.5.0.1 from /usr/local/lib/python2.7/site-packages/backports.ssl_match_hostname-3.5.0.1-py2.7.egg
      singledispatch: 3.4.0.3 from /usr/local/lib/python2.7/site-packages/singledispatch-3.4.0.3-py2.7.egg
        six: 1.10.0 from /usr/local/lib/python2.7/site-packages/six-1.10.0-py2.7.egg
      certifi: 2016.2.28 from /usr/local/lib/python2.7/site-packages/certifi-2016.2.28-py2.7.egg
      backports_abc>=0.4: 0.4 from /usr/local/lib/python2.7/site-packages/backports_abc-0.4-py2.7.egg
Mopidy-Pandora: 0.2.2 from /Users/jcass/PycharmProjects/Mopidy/mopidy-pandora
  setuptools: 20.7.0 from /usr/local/lib/python2.7/site-packages
  cachetools>=1.0.0: 1.1.5 from /usr/local/lib/python2.7/site-packages/cachetools-1.1.5-py2.7.egg
  Mopidy>=1.1.2: 2.0.0 from /Users/jcass/PycharmProjects/Mopidy/mopidy
    Pykka>=1.1: 1.2.1 from /usr/local/lib/python2.7/site-packages/Pykka-1.2.1-py2.7.egg
    requests>=2.0: 2.9.1 from /usr/local/lib/python2.7/site-packages
    setuptools: 20.7.0 from /usr/local/lib/python2.7/site-packages
    tornado>=2.3: 4.3 from /usr/local/lib/python2.7/site-packages/tornado-4.3-py2.7-macosx-10.11-x86_64.egg
      backports.ssl_match_hostname: 3.5.0.1 from /usr/local/lib/python2.7/site-packages/backports.ssl_match_hostname-3.5.0.1-py2.7.egg
      singledispatch: 3.4.0.3 from /usr/local/lib/python2.7/site-packages/singledispatch-3.4.0.3-py2.7.egg
        six: 1.10.0 from /usr/local/lib/python2.7/site-packages/six-1.10.0-py2.7.egg
      certifi: 2016.2.28 from /usr/local/lib/python2.7/site-packages/certifi-2016.2.28-py2.7.egg
      backports_abc>=0.4: 0.4 from /usr/local/lib/python2.7/site-packages/backports_abc-0.4-py2.7.egg
  Pykka>=1.1: 1.2.1 from /usr/local/lib/python2.7/site-packages/Pykka-1.2.1-py2.7.egg
  pydora>=1.7.0: 1.7.0 from /Users/jcass/PycharmProjects/Mopidy/pydora
    pycrypto>=2.6.1: 2.6.1 from /usr/local/lib/python2.7/site-packages
    requests>=2: 2.9.1 from /usr/local/lib/python2.7/site-packages
  requests>=2.5.0: 2.9.1 from /usr/local/lib/python2.7/site-packages
GStreamer: 1.8.0.0 from /usr/local/lib/python2.7/site-packages/gi
  Detailed information: 
    Python wrapper: python-gi 3.18.2
    Relevant elements:
      Found:
        uridecodebin
        souphttpsrc
        appsrc
        oss4sink
        id3demux
        id3v2mux
        lamemp3enc
        mad
        mpegaudioparse
        vorbisdec
        vorbisenc
        vorbisparse
        oggdemux
        oggmux
        oggparse
        flacdec
        flacparse
        shout2send
      Not found:
        alsasink
        osssink
        pulsesink
        flump3dec
        mpg123audiodec
```
If you have any more information then please let me know and we can take another look. Otherwise, I'm not sure why this is not working on your specific setup.

**Comment by Firestorrrm** [comment] 2016-04-20 18:37
I just figured it out...

For some reason, the wifi connection in my dormitory causes everything to go crazy once an ad is queued up, but if I switch to the main campus wifi, I no longer have the issue. It's a weird issue, but it works.

**Closed** 2016-04-21 04:38 UTC
