### ISSUE TITLE
Connects to Pandora...

### ISSUE THREAD

**Issue by quadnegative** [rectalogic/mopidy-pandora#14] opened 2015-07-10 18:29 UTC
and get album art, but does not stream audio.

**Comment by rectalogic** [comment] 2015-07-10 18:36
What is in the logs?

**Comment by quadnegative** [comment] 2015-07-10 18:41
2015-07-09 23:53:53,901 - INFO     Resetting dropped connection: tuner.pandora.com
2015-07-09 23:53:54,056 - INFO     Resetting dropped connection: tuner.pandora.com
2015-07-09 23:53:54,523 - INFO     Starting new HTTPS connection (1): tuner.pandora.com
2015-07-09 23:53:55,110 - INFO     Starting new HTTP connection (1): tuner.pandora.com
2015-07-09 23:54:00,830 - INFO     304 GET /images/default_cover.png (192.168.15.147) 7.20ms
2015-07-09 23:54:00,836 - INFO     304 GET /images/icons/play_alt_32x32.png (192.168.15.147) 3.49ms
2015-07-09 23:54:00,850 - INFO     304 GET /images/default_cover.png (192.168.15.147) 4.03ms
2015-07-09 23:54:00,856 - INFO     304 GET /images/icons/play_alt_32x32.png (192.168.15.147) 3.34ms
2015-07-09 23:54:01,190 - INFO     304 GET /images/icons/pause_32x32.png (192.168.15.147) 3.98ms
2015-07-09 23:54:01,204 - INFO     304 GET /images/icons/pause_32x32.png (192.168.15.147) 3.61ms
2015-07-09 23:54:01,237 - INFO     304 GET /images/icons/play_alt_12x12.png (192.168.15.147) 3.69ms

**Comment by quadnegative** [comment] 2015-07-10 19:33
I am running pi musicbox 0.6 it is running mopidy 0.19.5

I upgraded to mopidy 1.0.3. I now am getting different logs.

2015-07-10 00:42:25,324 - ERROR    Got un-handled exception from TuneInBackend
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/Mopidy-1.0.7-py2.7.egg/mopidy/commands.py", line 239, in _actor_erro
r_handling
    yield
  File "/usr/local/lib/python2.7/dist-packages/Mopidy-1.0.7-py2.7.egg/mopidy/commands.py", line 380, in start_backe
nds
    config=config, audio=audio).proxy()
  File "/usr/local/lib/python2.7/dist-packages/pykka/actor.py", line 93, in start
    obj = cls(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/mopidy_tunein/actor.py", line 23, in __init__
    backend=self, timeout=config['tunein']['timeout'])
  File "/usr/local/lib/python2.7/dist-packages/mopidy_tunein/actor.py", line 32, in __init__
    self._scanner = scan.Scanner(min_duration=None, timeout=timeout)
TypeError: __init__() got an unexpected keyword argument 'min_duration'
2015-07-10 00:42:25,335 - INFO     Starting Mopidy-Podcast directories: iTunesDirectory, FeedsDirectory, GPodderDir
ectory
2015-07-10 00:42:25,350 - INFO     Refreshing Mopidy-Podcast directories
2015-07-10 00:42:25,360 - INFO     Starting new HTTP connection (1): itunes.apple.com
2015-07-10 00:42:25,409 - INFO     Starting Mopidy core
2015-07-10 00:42:25,518 - INFO     Starting Mopidy frontends: MpdFrontend, HttpFrontend
2015-07-10 00:42:25,524 - INFO     MPD server running at [::ffff:0.0.0.0]:6600
2015-07-10 00:42:25,532 - INFO     HTTP server running at [::ffff:0.0.0.0]:6680
2015-07-10 00:42:31,954 - INFO     Starting new HTTP connection (1): tuner.pandora.com
2015-07-10 00:43:26,252 - INFO     304 GET /settings/ (192.168.15.147) 861.54ms
2015-07-10 00:43:27,080 - INFO     200 GET / (127.0.0.1) 30.47ms
2015-07-10 00:43:27,467 - WARNING  404 GET /favicon.ico (192.168.15.147) 3.33ms
2015-07-10 00:43:42,350 - ERROR    <ActorProxy for PandoraBackend (urn:uuid:0d83400e-9c1d-4383-88e0-12b771db8fb6),
attr_path=()> needs to be updated to work with this version of Mopidy.
2015-07-10 00:43:42,351 - WARNING  Track is not playable: pandora:track:153553713865538695:Flogging%20Molly%20Radio
%20%28Repeat%20Track%29:https%3A//www.pandora.com/login%3Ftarget%3D%252Fstations%252Fec6ae9b06ede7d7d893b2aeda40503
29c29045a5cf801fa8:http%3A//cont-sjl-2.pandora.com/images/public/amz/2/3/0/2/626570612032_500W_499H.jpg

Thoughts?

**Comment by rectalogic** [comment] 2015-07-10 19:53
Looks like mopidy has made some major changes to their api https://docs.mopidy.com/en/latest/changelog/

```ERROR    <ActorProxy for PandoraBackend (urn:uuid:0d83400e-9c1d-4383-88e0-12b771db8fb6),
attr_path=()> needs to be updated to work with this version of Mopidy.```

Need to go through the changelog and see what needs to be updated.

**Comment by quadnegative** [comment] 2015-07-10 20:50
Is there a mopidy version that is known to work?

**Comment by rectalogic** [comment] 2015-07-10 21:01
It was developed against mopidy 0.19.4

**Comment by jcass77** [comment] 2015-07-11 05:17
I've been using Mopidy 1.0.7 for some time. I think the error that @rectalogic pointed out in the log is due to Mopidy >= 1.0 making use of the new ```translate_ui()``` method.

I've created PR https://github.com/rectalogic/mopidy-pandora/pull/15 that should fix that, and add a few other minor tweaks.

**Comment by jcass77** [comment] 2015-07-11 05:23
...but I don't think any of this is related to the original issue, which appears to be as a result of the HTTP connection failing.

Can you perhaps run mopidy with debug logging enabled (```mopidy --save-debug-log```) and post the output here as well?

**Comment by jcass77** [comment] 2015-10-26 16:46
I haven't been able to reproduce this specific issue, though Mopidy-Pandora sometimes report tracks as unplayable if one of the Pandora [server error codes](http://6xq.net/pandora-apidoc/json/errorcodes/) occur.

Suggest that we close this issue in the absence of more information, as it is likely that the problem was on the server side, rather than a bug in Mopidy-Pandora.

**Closed by jcass77** 2015-10-26 16:46 UTC
