### ISSUE TITLE
Mopidy-pandora stops working after long periods of inactivity

### ISSUE THREAD

**Issue by jcass77** [rectalogic/mopidy-pandora#7] opened 2015-05-31 08:14 UTC
I sometimes leave Mopidy running for days on end on a Pi Musicbox. I've found that if I press pause after listening, and then try to resume playback or select different Pandora stations to listen to a few hours later, mopidy-pandora fails silently.

* If I push play to resume the current track, the following output appears in the debug log file:

```ERROR    2015-05-30 14:47:00,638 [5508:MainThread] mopidy.audio.gst
  Could not open resource for reading.```

* If I navigate to Browse -> Pandora -> Stations, then the 'Loading data from...' spinning wheel appears, but nothing is loaded and the station list is not displayed.

I suspect that the above is due to the Pandora session expiring at some point, and that we need to find a way to check that it is still active and re-initialise if necessary?

**Comment by jcass77** [comment] 2015-06-06 12:45
It looks like Pandora returns ```"listeningTimeoutMinutes":"180"``` (i.e. 3 hours?) when the user logs in initially, which may be related to the session timing out.

Pianobar supports automatic re-authentication as outlined at https://github.com/PromyLOPh/pianobar/commit/3a2e42b0cd164c0d52805b539353c5b12492e284

For this to work we will need to catch ```PandoraException``` with error code 1001, and then re-authenticate. I've never see any exceptions come through from pydora however, so not sure if we will be able to detect and handle this correctly.

**Comment by rectalogic** [comment] 2015-06-06 14:11
Mopidy-Pandora just hands the direct audio url to Mopidy https://github.com/rectalogic/mopidy-pandora/blob/master/mopidy_pandora/actor.py#L56

So Mopidy itself must be seeing some failure when trying to play the stream. It looks like it may try to play the next track on failure, which seems like it might work.
https://github.com/mopidy/mopidy/blob/develop/mopidy/core/playback.py#L348

So I would start there, insert a breakpoint in that code and wait for it to time out and see how Mopidy is handling it.

**Comment by jcass77** [comment] 2015-06-10 02:54
Based on what I've seen so far, the current track will continue playing if you just click the push/play button again (I assume that Mopidy buffers the entire song before the session expires anyway).

I've started working on an implementation that catches the 'Invalid Auth Token' exceptions that are raised by Pandora, and then tries to perform the last action again (an early preview can be seen at https://github.com/jcass77/mopidy-pandora/commit/cc645de6b43fac4082db3450c8066d2fac1c820c).

It appears to be working but I'd like to test it for a few days before creating a pull request. Unfortunately testing is a slow process as one has to wait three hours between runs for the Pandora session to expire.

**Comment by jcass77** [comment] 2015-06-13 06:12
Candidate solution proposed in pull request https://github.com/rectalogic/mopidy-pandora/pull/9.

**Comment by jcass77** [comment] 2015-07-11 05:53
I haven't had any further problems with this since the merge of https://github.com/rectalogic/mopidy-pandora/pull/9. 

There are a few related outlier conditions that @mcrute is working on addressing in the pydora API (https://github.com/mcrute/pydora/issues/14, https://github.com/mcrute/pydora/issues/19, and maybe https://github.com/mcrute/pydora/issues/20 which I may also have encountered), but in general just going back to browsing the list of Pandora stations in Mopidy resets everything and allows the user to play the next track without having to restart Mopidy completely.

I suggest that we close this issue as it is no longer a major problem, and upcoming changes to the underlying pydora API will make keeping the connection running for long periods of time much more robust in future releases as well.

**Comment by mcrute** [comment] 2015-07-11 20:02
Issue mcrute/pydora#20 shouldn't affect Mopidy-pandora, it's a specific issue with the way the bundled pydora command line player uses mpg123 for streaming behind the scenes. Fixing mcrute/pydora#14 will allow you to remove the `authenticated` decorator in `pydora.py` and the methods that use it since that will fix the issue in pydora itself and is a transitive fix in the models that the API returns. Issue mcrute/pydora#19 may not affect you yet but from what I can tell now it's a regression introduced on python3 with the replacement of `urllib` with `requests`. Do you target python3 compatibility?

**Comment by rectalogic** [comment] 2015-07-28 20:26
> I suggest that we close this issue as it is no longer a major problem

Closing.

**Closed by rectalogic** 2015-07-28 20:26 UTC
